---
aap_hostname: "aap.apps.hub.aws.tntinfra.net"
aap_validate_certs: false
aap_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
    38633762303935353166656364663735636437353166346136326462653138656537356235306638
  3565646231626139636339323662393064666638663237660a353834346538396361636137653432
  66653963303462616665636632653238316639353466343931666631396463376136313362306333
  3934343735613239660a386437336332663038333931353964616466633439386330663164356335
  63636237633536653333383839633665353133306261663466306666653966363963