---
aap_hostname: "aap.apps.hub.aws.tntinfra.net"
aap_validate_certs: false
aap_token: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65303535396430313134653465313330623432333138316537376464326239306438343763376630
  3262376563666338306165336538613935633862353661360a346332303635313534636666336461
  37363930373737646164356334336538613737326130316538663339376564386337306637326437
  6666343133396532630a613863616335366139623534353765343432336239393536613364306461
  37643462633434343239643161393838363537346562616231636666636264323837386466363331
  6331306365343331663637393233346563336333336439626233